import html


def build_report(task, result):
    model = result.get("model", {})
    model_name = model.get("model_name", "Unknown model") if isinstance(model, dict) else str(model)
    rows = []
    total_points = len(result["points"])
    failed_points = sum(1 for point in result["points"] if point["status"].lower() != "success")
    success_points = total_points - failed_points

    for point in result["points"]:
        status = "success" if point["status"].lower() == "success" else "failed"
        detail = (
            f'max altitude {point["max_altitude_m"]:.1f} m, '
            f'max speed {point["max_speed_kmh"]:.1f} km/h'
            if point["status"].lower() == "success"
            else html.escape(point["message"])
        )
        rows.append(
            f"<tr><td>{html.escape(point['id'])}</td><td>{status}</td><td>{detail}</td></tr>"
        )

    return f"""<!doctype html>
	<html lang="en"><head><meta charset="utf-8"><title>Flight Simulation Report</title>
<style>
body{{font:15px/1.7 Arial,sans-serif;color:#17222d;max-width:920px;margin:40px auto;padding:0 32px}}
h1{{font-size:28px;border-bottom:3px solid #2b6777;padding-bottom:14px}}
.meta{{display:grid;grid-template-columns:repeat(2,1fr);background:#f2f5f4;padding:18px 24px}}
table{{width:100%;border-collapse:collapse;margin-top:20px}}th,td{{padding:11px;border-bottom:1px solid #ccd5d2;text-align:left}}
th{{background:#163b3d;color:white}}.stamp{{color:#63716f;margin-top:36px}}
</style></head><body>
<h1>Flight Simulation Report</h1>
<div class="meta">
<div><strong>Task</strong><br>{html.escape(str(task.get("task_code") or ""))}</div>
<div><strong>Subject</strong><br>{html.escape(result["subject"])}</div>
<div><strong>Model</strong><br>{html.escape(model_name)}</div>
<div><strong>Finished At</strong><br>{html.escape(str(task.get("finished_at") or ""))}</div>
</div>
	<p><strong>Script:</strong> {html.escape(str(task.get("script_code") or ""))}</p>
	<h2>Summary</h2>
	<p>Total {total_points}, succeeded {success_points}, failed {failed_points}.</p>
<table><thead><tr><th>Point</th><th>Status</th><th>Detail</th></tr></thead>
<tbody>{''.join(rows)}</tbody></table>
<h2>Output Parameters</h2>
<p>{html.escape(', '.join(task.get("output_parameters") or []))}</p>
<p class="stamp">Generated by the flight simulation backend.</p>
</body></html>"""
